---
- name: Deploy app and create service in k8s
  hosts: localhost
  connection: local
  become_user: jenkins
  become: true
  gather_facts: no
  tasks:
    - name: Deploy deployment and service in k8s cluster
      shell: "kubectl create -f deployment_service.yml"

